---
abstract: 'AdaGrad learning algorithm.'
author:
  - 'hideo55 <hide.o.j55@gmail.com>'
build_requires:
  File::Temp: '0'
  Test::Fatal: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::XSUtil: '0.14'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Algorithm-AdaGrad
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
requires:
  perl: '5.012'
resources:
  bugtracker: https://github.com/hideo55/p5-Algorithm-AdaGrad/issues
  homepage: https://github.com/hideo55/p5-Algorithm-AdaGrad
  repository: git://github.com/hideo55/p5-Algorithm-AdaGrad.git
version: 0.01_01
x_authority: cpan:HIDEAKIO
